pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/YashwanthP2329/ecommerce-devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ecommerce-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker stop ecommerce-container || true'
                sh 'docker rm ecommerce-container || true'
                sh 'docker run -d -p 5000:5000 --name ecommerce-container ecommerce-app'
            }
        }
    }
}