pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/YashwanthP2329/ecommerce-devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t ecommerce-app .'
            }
        }

        stage('Remove Old Container') {
            steps {
                bat 'docker rm -f ecommerce-container'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 5000:5000 --name ecommerce-container ecommerce-app'
            }
        }
    }
}